export type {
  AddBotResponse,
  ClientToServerEvents,
  CreateRoomResponse,
  EventVisibility,
  FillSeatsWithBotsResponse,
  GameActionResponse,
  GamePhase,
  GameEvent,
  GamePlayerView as NetworkGamePlayer,
  GameStateView,
  JoinRoomResponse,
  LeaveRoomResponse,
  ProposalStage,
  QuestAction,
  QuestDetail,
  Role,
  RoleCardID,
  RoomPlayerView as NetworkPlayer,
  RoomStatus,
  RoomView,
  ServerToClientEvents,
  StartGameResponse,
  Team,
  VoteChoice,
} from "../../../shared/types/sharedTypes";

export type Page = "home" | "room" | "game" | "gameOver";
